#!/bin/bash
bin_dir="$(dirname $(readlink -f $0))"/bin
echo Creating links to scripts in $bin_dir inside /usr/local/bin/ ...
for target in $(find $bin_dir -type f -executable); do
	echo "  Linking \"$target\" ..."
	sudo ln -fs "$target" /usr/local/bin/
	(( $? )) && err=yes
done
test -n "$err" && echo WARNING: There were errors. Please check.
echo Done
